name: lucky_touch_app
description: AWelcome to Lucky Touch!
  
  Touch, hold, and let the app pick a winner — perfect for games, decisions, and group fun!

✨ What's included:
  - Simple hold-to-start gameplay for 2+ players
  - Auto & Manual selection modes
  - Multiple finger styles: Ring, Dot, and Fingerprint
  - Colorful, vibrant design
  - Lightweight and works offline


publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

dependency_overrides:
  archive: ^3.6.1

# ✅ Add this at root level
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true